REQUIRED_CATEGORIES = [
    "ACTA DE MATRIMONIO",
    "ACTIVOS (PROPIEDADES Y VEHICULOS)",
    "BOLETAS DE PAGO O CUENTAS DE PAGO",
    "CONSTANCIAS DE ESTUDIOS O CV",
    "DNI",
    "DOCUMENTOS ADICIONALES",
    "EMPRESAS O CONSTANCIA DE TRABAJO",
    "ESTADOS DE CUENTA X 6 MESES",
    "FOTO",
    "PASAPORTE",
]
